PRODUCT_NAME := $(CGSI_CUSTOM_ROM)_$(CGSI_PRODUCT_DEVICE)
PRODUCT_DEVICE := $(CGSI_PRODUCT_DEVICE)
PRODUCT_BRAND := CGSI
PRODUCT_MANUFACTURER := CGSI
PRODUCT_MODEL := Custom GSI for $(CGSI_ARCH) $(CGSI_DEVICE_TYPE)

PRODUCT_GMS_CLIENTID_BASE ?= android-google
